name: E2E Tests

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - dev
            - main
    workflow_dispatch:

jobs:
    cypress-run:
      runs-on: ubuntu-latest

      steps:
        # Checkout the codebase
        - name: Checkout repository
          uses: actions/checkout@v7

        - name: Set up Node.js
          uses: actions/setup-node@v6
          with:
            node-version: 24
            # This caches the downloaded packages between workflows...make it faster
            cache: npm
        - name: Install Dependencies
            # ensures npm install uses your package-lock.json
          run: npm ci
        - name: execute cypress
          uses: cypress-io/github-action@v7
          with:
            browser: electron
            start: npm run dev
            wait-on: http://localhost:5173/
        